#Control file for cibuildwheel (generate PIP wheels using github actions)

[build-system]
build-backend = 'mesonpy'
requires = ['meson-python']

[tool.cibuildwheel.macos]
build = ['cp37-macosx_x86_64']

[tool.cibuildwheel.windows]
build = ['cp37-win_amd64']
repair-wheel-command = ""

[tool.cibuildwheel.linux]
build = ['cp38-manylinux_x86_64']

[tool.meson-python.args]
compile = ['-vvv']


