"""A wrapper class for working with PSF/PRF maps from the C/C++ library."""

from superphot._initialize_library import superphot_library
from superphot. smooth_dependence import SmoothDependence

class PSFMap:
    """Provide convenient python interface to shape fitting results."""

    def __init__(self, star_shape_map_tree):
        """
        Prepare to query the map generated by a star shape fit.

        Args:
            star_shape_map_tree(SuperPhotIOTree):    The result returned by
                calling FitStarShape.fit().

        Returns:
            None
        """

        self._library_map = superphot_library.create_piecewise_bicubic_psf_map(
            star_shape_map_tree.library_tree
        )
        self._map_terms = SmoothDependence.expand_expression(
            star_shape_map_tree.get('psf.terms')
        )

    def __call__(self, **map_variables):
        """
        Evaluate the map for a given set of values of the map variables.

        Args:
            map_variables:    Should define values for all variables on which
                the map depends.

        Returns:
            PSF:
                The PSF/PRF the map predicts for the given arguments.
        """

        term_values = SmoothDependence.evaluate_terms(self._map_terms,
                                                      **map_variables)

    def __del__(self):
        """Delete any objects allocated by the library."""

        superphot_library.destroy_piecewise_bicubic_psf_map(self._library_map)
